### ISSUE TITLE
Screen capture exception

### ISSUE THREAD

**Issue by caisq** [TeamGleason/SpeakFaster#27]
When the observer is running along with Balabolka, the following exception is thrown during the first screen capture

Exception thrown: 'System.BadImageFormatException' in libjpeg-turbo-net.dll
Exception thrown: 'System.TypeInitializationException' in SpeakFasterObserver.dll
An exception of type 'System.TypeInitializationException' occurred in SpeakFasterObserver.dll but was not handled in user code
The type initializer for 'SpeakFasterObserver.ScreenCapture' threw an exception.

'SpeakFasterObserver.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[5352] SpeakFasterObserver.exe' has exited with code -1 (0xffffffff).

**Comment by joncamp** [comment]
I have seen the same issue. @TeamGleasonDev  would know more about it.

Workaround is to turn off screenshot capture (assuming you are ok with just looking at keystrokes)

**Comment by joncamp** [comment]
System.ArgumentException
  HResult=0x80070057
  Message=Parameter is not valid.
  Source=System.Drawing.Common
  StackTrace:
   at System.Drawing.Graphics.GetHdc() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.cs:line 338
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.Windows.cs:line 252
   at SpeakFasterObserver.ScreenCapture.CaptureDesktop(Boolean workingAreaOnly) in C:\Users\joncamp\source\repos\joncamp\SpeakFaster\Observer\SpeakFasterObserver\ScreenCapture.cs:line 86
   at SpeakFasterObserver.ScreenCapture.Capture(String path, String timestamp) in C:\Users\joncamp\source\repos\joncamp\SpeakFaster\Observer\SpeakFasterObserver\ScreenCapture.cs:line 141
   at SpeakFasterObserver.FormMain.CaptureScreenshot(String timestamp, String filePath) in C:\Users\joncamp\source\repos\joncamp\SpeakFaster\Observer\SpeakFasterObserver\FormMain.cs:line 209
   at SpeakFasterObserver.FormMain.screenshotTimer_Tick(Object sender, EventArgs e) in C:\Users\joncamp\source\repos\joncamp\SpeakFaster\Observer\SpeakFasterObserver\FormMain.cs:line 136
   at System.Windows.Forms.Timer.OnTick(EventArgs e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs:line 173
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs:line 354
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 372
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs:line 345
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 1111
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 975
   at System.Windows.Forms.Application.Run(Form mainForm) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1198
   at SpeakFasterObserver.Program.Main() in C:\Users\joncamp\source\repos\joncamp\SpeakFaster\Observer\SpeakFasterObserver\Program.cs:line 25

  This exception was originally thrown at this call stack:
    System.Drawing.Graphics.GetHdc() in Graphics.cs
    System.Drawing.Graphics.CopyFromScreen(int, int, int, int, System.Drawing.Size, System.Drawing.CopyPixelOperation) in Graphics.Windows.cs
    SpeakFasterObserver.ScreenCapture.CaptureDesktop(bool) in ScreenCapture.cs
    SpeakFasterObserver.ScreenCapture.Capture(string, string) in ScreenCapture.cs
    SpeakFasterObserver.FormMain.CaptureScreenshot(string, string) in FormMain.cs
    SpeakFasterObserver.FormMain.screenshotTimer_Tick(object, System.EventArgs) in FormMain.cs
    System.Windows.Forms.Timer.OnTick(System.EventArgs) in Timer.cs
    System.Windows.Forms.Timer.TimerNativeWindow.WndProc(ref System.Windows.Forms.Message) in Timer.cs
    System.Windows.Forms.NativeWindow.Callback(System.IntPtr, Interop.User32.WM, System.IntPtr, System.IntPtr) in NativeWindow.cs
    System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(System.UIntPtr, Interop.Mso.msoloop, void*) in Application.ComponentManager.cs
    ...
    [Call Stack Truncated]

**Comment by joncamp** [comment]
Could be this: https://social.msdn.microsoft.com/Forums/en-US/c6f33dfe-3ec1-4f17-9e3c-8497f48d4190/parameter-is-not-valid-after-being-valid-for-millions-of-iterations?forum=vbgeneral

'''
System.ArgumentException
  HResult=0x80070057
  Message=Parameter is not valid.
  Source=System.Drawing.Common
  StackTrace:
   at System.Drawing.Graphics.GetHdc() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.cs:line 338
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.Windows.cs:line 252
   at SpeakFasterObserver.ScreenCapture.CaptureDesktop(Boolean workingAreaOnly) in C:\Users\joncamp\source\repos\joncamp\SpeakFaster\Observer\SpeakFasterObserver\ScreenCapture.cs:line 86
   at SpeakFasterObserver.ScreenCapture.Capture(String path, String timestamp) in C:\Users\joncamp\source\repos\joncamp\SpeakFaster\Observer\SpeakFasterObserver\ScreenCapture.cs:line 141
   at SpeakFasterObserver.FormMain.CaptureScreenshot(String timestamp, String filePath) in C:\Users\joncamp\source\repos\joncamp\SpeakFaster\Observer\SpeakFasterObserver\FormMain.cs:line 209
   at SpeakFasterObserver.FormMain.screenshotTimer_Tick(Object sender, EventArgs e) in C:\Users\joncamp\source\repos\joncamp\SpeakFaster\Observer\SpeakFasterObserver\FormMain.cs:line 136
   at System.Windows.Forms.Timer.OnTick(EventArgs e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs:line 173
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs:line 354
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 372
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs:line 345
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 1111
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 975
   at System.Windows.Forms.Application.Run(Form mainForm) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1198
   at SpeakFasterObserver.Program.Main() in C:\Users\joncamp\source\repos\joncamp\SpeakFaster\Observer\SpeakFasterObserver\Program.cs:line 25

  This exception was originally thrown at this call stack:
    System.Drawing.Graphics.GetHdc() in Graphics.cs
    System.Drawing.Graphics.CopyFromScreen(int, int, int, int, System.Drawing.Size, System.Drawing.CopyPixelOperation) in Graphics.Windows.cs
    SpeakFasterObserver.ScreenCapture.CaptureDesktop(bool) in ScreenCapture.cs
    SpeakFasterObserver.ScreenCapture.Capture(string, string) in ScreenCapture.cs
    SpeakFasterObserver.FormMain.CaptureScreenshot(string, string) in FormMain.cs
    SpeakFasterObserver.FormMain.screenshotTimer_Tick(object, System.EventArgs) in FormMain.cs
    System.Windows.Forms.Timer.OnTick(System.EventArgs) in Timer.cs
    System.Windows.Forms.Timer.TimerNativeWindow.WndProc(ref System.Windows.Forms.Message) in Timer.cs
    System.Windows.Forms.NativeWindow.Callback(System.IntPtr, Interop.User32.WM, System.IntPtr, System.IntPtr) in NativeWindow.cs
    System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(System.UIntPtr, Interop.Mso.msoloop, void*) in Application.ComponentManager.cs
    ...
    [Call Stack Truncated]
'''
